title: Tejaswini Dasari
image: https://github.com/Tejaswini-dasari/portfolio/blob/main/assets/teju.jpg
image_width: 300px
image_height: auto
description: text below image
show_download: true
theme: jekyll-theme-minimal
